version: "3.8"

services:
  redis:
    image: redis:7.0-alpine
    container_name: "my_redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  redis_data:
