version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: "my_rabbitmq"
    ports:
      - "5672:5672"      # AMQP protocol port
      - "15672:15672"    # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my_network

  redis:
    image: redis:7.0-alpine
    container_name: "my_redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  rabbitmq_data:
  redis_data:
